/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_akhir_pbo;

/**
 *
 * @author User
 */
public class CRUD extends javax.swing.JFrame {

    /**
     * Creates new form CreateMobil
     */
    public CRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        PanelButton = new javax.swing.JPanel();
        ChooseVehicle = new javax.swing.JComboBox<>();
        CreateButtonVehicle = new javax.swing.JButton();
        UpdateButtonVehicle = new javax.swing.JButton();
        BackButtonVehicle = new javax.swing.JButton();
        DeleteButtonVehicle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        menuTruk = new javax.swing.JPanel();
        CreateTruk = new javax.swing.JPanel();
        CreateIDKendaraan = new javax.swing.JTextField();
        CreateModel = new javax.swing.JComboBox<>();
        CreateUkuranMesin = new javax.swing.JComboBox<>();
        CreateWarna = new javax.swing.JComboBox<>();
        CreateKapasitasBak = new javax.swing.JComboBox<>();
        CreateJenisBak = new javax.swing.JComboBox<>();
        CreateTabelScroll = new javax.swing.JScrollPane();
        CreateTableTruk = new javax.swing.JTable();
        menuMobil = new javax.swing.JPanel();
        CreateMobil = new javax.swing.JPanel();
        IDMobil = new javax.swing.JTextField();
        ModelMobil = new javax.swing.JComboBox<>();
        UkuranMesinMobil = new javax.swing.JComboBox<>();
        WarnaMobil = new javax.swing.JComboBox<>();
        PenumpangMobil = new javax.swing.JComboBox<>();
        JumlahPintu = new javax.swing.JComboBox<>();
        TabelMobil = new javax.swing.JScrollPane();
        TableMobil = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(204, 255, 204));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelButton.setBackground(new java.awt.Color(255, 51, 51));
        PanelButton.setPreferredSize(new java.awt.Dimension(800, 90));

        ChooseVehicle.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        ChooseVehicle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRUCK", "CAR" }));
        ChooseVehicle.setPreferredSize(new java.awt.Dimension(72, 23));
        ChooseVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseVehicleActionPerformed(evt);
            }
        });

        CreateButtonVehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateButtonVehicle.setText("CREATE");
        CreateButtonVehicle.setPreferredSize(new java.awt.Dimension(80, 30));
        CreateButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonVehicleActionPerformed(evt);
            }
        });

        UpdateButtonVehicle.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        UpdateButtonVehicle.setText("UPDATE");
        UpdateButtonVehicle.setPreferredSize(new java.awt.Dimension(80, 30));
        UpdateButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonVehicleActionPerformed(evt);
            }
        });

        BackButtonVehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackButtonVehicle.setText("BACK");
        BackButtonVehicle.setPreferredSize(new java.awt.Dimension(80, 30));
        BackButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonVehicleActionPerformed(evt);
            }
        });

        DeleteButtonVehicle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DeleteButtonVehicle.setText("DELETE");
        DeleteButtonVehicle.setPreferredSize(new java.awt.Dimension(80, 30));
        DeleteButtonVehicle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonVehicleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelButtonLayout = new javax.swing.GroupLayout(PanelButton);
        PanelButton.setLayout(PanelButtonLayout);
        PanelButtonLayout.setHorizontalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(ChooseVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CreateButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(UpdateButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DeleteButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addComponent(BackButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelButtonLayout.setVerticalGroup(
            PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelButtonLayout.createSequentialGroup()
                .addGroup(PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelButtonLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(PanelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CreateButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChooseVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpdateButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelButtonLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BackButtonVehicle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        MainPanel.add(PanelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 90));

        jPanel1.setLayout(new java.awt.CardLayout());

        menuTruk.setLayout(new java.awt.CardLayout());

        CreateTruk.setBackground(new java.awt.Color(102, 102, 102));
        CreateTruk.setPreferredSize(new java.awt.Dimension(800, 500));
        CreateTruk.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CreateIDKendaraan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateIDKendaraan.setText("VEHICLE ID");
        CreateIDKendaraan.setPreferredSize(new java.awt.Dimension(180, 55));
        CreateIDKendaraan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CreateIDKendaraanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CreateIDKendaraanFocusLost(evt);
            }
        });
        CreateIDKendaraan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateIDKendaraanActionPerformed(evt);
            }
        });
        CreateTruk.add(CreateIDKendaraan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 16, 220, -1));

        CreateModel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateModel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODEL", "Light", "Medium", "Heavy" }));
        CreateModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateModelActionPerformed(evt);
            }
        });
        CreateTruk.add(CreateModel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 61));

        CreateUkuranMesin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateUkuranMesin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENGINE", "4500 CC", "5500 CC", "7500 CC" }));
        CreateUkuranMesin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateUkuranMesinActionPerformed(evt);
            }
        });
        CreateTruk.add(CreateUkuranMesin, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 16, 220, 55));

        CreateWarna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateWarna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COLOR", "Yellow", "Green", "Orange" }));
        CreateWarna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateWarnaActionPerformed(evt);
            }
        });
        CreateTruk.add(CreateWarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 90, 220, 61));

        CreateKapasitasBak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateKapasitasBak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BED CAPACITY", "4 TONS", "8 TONS", "15 TONS" }));
        CreateTruk.add(CreateKapasitasBak, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 220, 61));

        CreateJenisBak.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateJenisBak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BED TYPE", "FLAT", "BOX" }));
        CreateTruk.add(CreateJenisBak, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 15, 220, 57));

        CreateTableTruk.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateTableTruk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ENGINE", "MODEL", "COLOR", "BED TYPE", "BED CAPACITY", "DOKUMEN"
            }
        ));
        CreateTableTruk.setPreferredSize(new java.awt.Dimension(450, 90));
        CreateTabelScroll.setViewportView(CreateTableTruk);

        CreateTruk.add(CreateTabelScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 169, 740, 385));

        menuTruk.add(CreateTruk, "card2");

        jPanel1.add(menuTruk, "card3");

        menuMobil.setLayout(new java.awt.CardLayout());

        CreateMobil.setBackground(new java.awt.Color(102, 102, 102));
        CreateMobil.setPreferredSize(new java.awt.Dimension(800, 500));
        CreateMobil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IDMobil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        IDMobil.setText("VEHICLE ID");
        IDMobil.setPreferredSize(new java.awt.Dimension(180, 55));
        IDMobil.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDMobilFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDMobilFocusLost(evt);
            }
        });
        IDMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDMobilActionPerformed(evt);
            }
        });
        CreateMobil.add(IDMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 16, 220, -1));

        ModelMobil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ModelMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MODEL", "SEDAN", "MPV", "SUV" }));
        ModelMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelMobilActionPerformed(evt);
            }
        });
        CreateMobil.add(ModelMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 220, 61));

        UkuranMesinMobil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        UkuranMesinMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENGINE", "1500 CC", "1500 CC TURBO", "2000 CC", "2500 CC TURBO", "3000 CC" }));
        UkuranMesinMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UkuranMesinMobilActionPerformed(evt);
            }
        });
        CreateMobil.add(UkuranMesinMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 16, 220, 55));

        WarnaMobil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        WarnaMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COLOR", "WHITE", "BLACK", "RED", "YELLOW", "BLUE", "GRAY", "SILVER" }));
        WarnaMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WarnaMobilActionPerformed(evt);
            }
        });
        CreateMobil.add(WarnaMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 90, 220, 61));

        PenumpangMobil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PenumpangMobil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PASSENGER", "5", "7" }));
        CreateMobil.add(PenumpangMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 220, 61));

        JumlahPintu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JumlahPintu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOORS", "2", "4" }));
        CreateMobil.add(JumlahPintu, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 15, 220, 57));

        TableMobil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TableMobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "ENGINE", "MODEL", "COLOR", "DOORS", "PASSENGER", "DOKUMEN"
            }
        ));
        TableMobil.setPreferredSize(new java.awt.Dimension(450, 90));
        TabelMobil.setViewportView(TableMobil);

        CreateMobil.add(TabelMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 169, 740, 385));

        menuMobil.add(CreateMobil, "card2");

        jPanel1.add(menuMobil, "card3");

        MainPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateWarnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateWarnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateWarnaActionPerformed

    private void CreateIDKendaraanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateIDKendaraanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateIDKendaraanActionPerformed

    private void CreateModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateModelActionPerformed

    private void CreateIDKendaraanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CreateIDKendaraanFocusGained
       if(CreateIDKendaraan.getText().equals("Input ID Kendaraan")) {
           CreateIDKendaraan.setText("");
       }
    }//GEN-LAST:event_CreateIDKendaraanFocusGained

    private void CreateIDKendaraanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CreateIDKendaraanFocusLost
        if(CreateIDKendaraan.getText().isEmpty()){
            CreateIDKendaraan.setText("Input ID Kendaraan");
        }
    }//GEN-LAST:event_CreateIDKendaraanFocusLost

    private void ChooseVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseVehicleActionPerformed
        if (ChooseVehicle.getSelectedItem().equals("CAR")) {
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
                     
            jPanel1.add(menuMobil);
            jPanel1.repaint();
            jPanel1.revalidate();
        } else if (ChooseVehicle.getSelectedItem().equals("TRUCK")){
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            
            jPanel1.add(menuTruk);
            jPanel1.repaint();
            jPanel1.revalidate();
        }
    }//GEN-LAST:event_ChooseVehicleActionPerformed

    private void CreateUkuranMesinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateUkuranMesinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateUkuranMesinActionPerformed

    private void CreateButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateButtonVehicleActionPerformed

    private void BackButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonVehicleActionPerformed

    private void UpdateButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonVehicleActionPerformed

    private void DeleteButtonVehicleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonVehicleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtonVehicleActionPerformed

    private void IDMobilFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDMobilFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_IDMobilFocusGained

    private void IDMobilFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDMobilFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_IDMobilFocusLost

    private void IDMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDMobilActionPerformed

    private void ModelMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModelMobilActionPerformed

    private void UkuranMesinMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UkuranMesinMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UkuranMesinMobilActionPerformed

    private void WarnaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WarnaMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WarnaMobilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButtonVehicle;
    private javax.swing.JComboBox<String> ChooseVehicle;
    private javax.swing.JButton CreateButtonVehicle;
    private javax.swing.JTextField CreateIDKendaraan;
    private javax.swing.JComboBox<String> CreateJenisBak;
    private javax.swing.JComboBox<String> CreateKapasitasBak;
    private javax.swing.JPanel CreateMobil;
    private javax.swing.JComboBox<String> CreateModel;
    private javax.swing.JScrollPane CreateTabelScroll;
    private javax.swing.JTable CreateTableTruk;
    private javax.swing.JPanel CreateTruk;
    private javax.swing.JComboBox<String> CreateUkuranMesin;
    private javax.swing.JComboBox<String> CreateWarna;
    private javax.swing.JButton DeleteButtonVehicle;
    private javax.swing.JTextField IDMobil;
    private javax.swing.JComboBox<String> JumlahPintu;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JComboBox<String> ModelMobil;
    private javax.swing.JPanel PanelButton;
    private javax.swing.JComboBox<String> PenumpangMobil;
    private javax.swing.JScrollPane TabelMobil;
    private javax.swing.JTable TableMobil;
    private javax.swing.JComboBox<String> UkuranMesinMobil;
    private javax.swing.JButton UpdateButtonVehicle;
    private javax.swing.JComboBox<String> WarnaMobil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menuMobil;
    private javax.swing.JPanel menuTruk;
    // End of variables declaration//GEN-END:variables
}
